#!/bin/bash
# Build _riegeli_dataset_ops.so against TF 2.20 headers without Bazel.
#
# Uses TF 2.20's bundled Abseil + protobuf headers so there are no
# version mismatches at runtime.
set -e

TF_DIR="/home/kevin/workspace/kd_chess/.venv/lib/python3.12/site-packages/tensorflow"
TF_INC="$TF_DIR/include"
RIEGELI_DIR="/home/kevin/workspace/riegeli"
EXT="$RIEGELI_DIR/bazel-riegeli/external"
# Proto files generated by protoc 28.3 (matches TF 2.20)
GEN="$RIEGELI_DIR/build_manual"

OUTDIR="$RIEGELI_DIR/build_manual/obj"
mkdir -p "$OUTDIR"

CXX=g++
CXXFLAGS=(
    -std=c++17
    -O2
    -DNDEBUG
    -fPIC
    -D_GLIBCXX_USE_CXX11_ABI=1
    -DEIGEN_MAX_ALIGN_BYTES=64
    -fvisibility=hidden
    # TF headers FIRST — includes Abseil 20250127 + protobuf 5.28
    -isystem "$TF_INC"
    # Riegeli source tree
    -I "$RIEGELI_DIR"
    # Generated proto .pb.h files
    -I "$GEN"
    # Third-party sources (NO com_google_absl — use TF's)
    -I "$EXT/highwayhash"
    -I "$EXT/org_brotli/c/include"
    -I "$EXT/net_zstd"
    -I "$EXT/snappy"
    -I "$RIEGELI_DIR/bazel-riegeli/bazel-out/k8-opt/bin/external/snappy"
)

echo "=== Compiling ==="

RIEGELI_SRCS=(
    riegeli/base/assert.cc
    riegeli/base/background_cleaning.cc
    riegeli/base/buffer.cc
    riegeli/base/chain.cc
    riegeli/base/cord_utils.cc
    riegeli/base/errno_mapping.cc
    riegeli/base/memory_estimator.cc
    riegeli/base/object.cc
    riegeli/base/parallelism.cc
    riegeli/base/recycling_pool.cc
    riegeli/base/shared_buffer.cc
    riegeli/base/sized_shared_buffer.cc
    riegeli/base/status.cc
    riegeli/base/string_utils.cc
    riegeli/base/zeros.cc
    riegeli/brotli/brotli_allocator.cc
    riegeli/brotli/brotli_dictionary.cc
    riegeli/brotli/brotli_reader.cc
    riegeli/bytes/array_backward_writer.cc
    riegeli/bytes/backward_writer.cc
    riegeli/bytes/buffer_options.cc
    riegeli/bytes/buffered_reader.cc
    riegeli/bytes/chain_backward_writer.cc
    riegeli/bytes/chain_reader.cc
    riegeli/bytes/chain_writer.cc
    riegeli/bytes/cord_reader.cc
    riegeli/bytes/limiting_backward_writer.cc
    riegeli/bytes/limiting_reader.cc
    riegeli/bytes/pullable_reader.cc
    riegeli/bytes/pushable_backward_writer.cc
    riegeli/bytes/reader.cc
    riegeli/bytes/restricted_chain_writer.cc
    riegeli/bytes/string_reader.cc
    riegeli/bytes/string_writer.cc
    riegeli/bytes/write_int_internal.cc
    riegeli/bytes/writer.cc
    riegeli/chunk_encoding/chunk.cc
    riegeli/chunk_encoding/chunk_decoder.cc
    riegeli/chunk_encoding/decompressor.cc
    riegeli/chunk_encoding/field_projection.cc
    riegeli/chunk_encoding/hash.cc
    riegeli/chunk_encoding/simple_decoder.cc
    riegeli/chunk_encoding/transpose_decoder.cc
    riegeli/messages/message_parse.cc
    riegeli/messages/message_wire_format.cc
    riegeli/ordered_varint/ordered_varint_reading.cc
    riegeli/ordered_varint/ordered_varint_writing.cc
    riegeli/records/chunk_reader.cc
    riegeli/records/record_position.cc
    riegeli/records/record_reader.cc
    riegeli/records/skipped_region.cc
    riegeli/snappy/snappy_reader.cc
    riegeli/snappy/snappy_streams.cc
    riegeli/tensorflow/io/file_reader.cc
    riegeli/tensorflow/kernels/riegeli_dataset_ops.cc
    riegeli/tensorflow/ops/riegeli_dataset_ops.cc
    riegeli/varint/varint_reading.cc
    riegeli/zstd/zstd_dictionary.cc
    riegeli/zstd/zstd_reader.cc
)

# Proto .pb.cc is NOT compiled — TF 2.20 already exports RecordsMetadata
# symbols. Compiling it here causes proto double-registration crashes.
# We only need the .pb.h header (in $GEN) for compilation.
PROTO_SRCS=()

THIRDPARTY_SRCS=(
    "$EXT/highwayhash/highwayhash/sip_hash.cc"
    "$EXT/highwayhash/highwayhash/arch_specific.cc"
    "$EXT/highwayhash/highwayhash/instruction_sets.cc"
    "$EXT/highwayhash/highwayhash/nanobenchmark.cc"
    "$EXT/highwayhash/highwayhash/os_specific.cc"
    "$EXT/snappy/snappy.cc"
    "$EXT/snappy/snappy-sinksource.cc"
)

# highwayhash SSE41/AVX2 files need special flags
HH_SSE41_SRCS=("$EXT/highwayhash/highwayhash/hh_sse41.cc")
HH_AVX2_SRCS=("$EXT/highwayhash/highwayhash/hh_avx2.cc")

BROTLI_C_SRCS=(
    "$EXT/org_brotli/c/common/constants.c"
    "$EXT/org_brotli/c/common/context.c"
    "$EXT/org_brotli/c/common/dictionary.c"
    "$EXT/org_brotli/c/common/platform.c"
    "$EXT/org_brotli/c/common/shared_dictionary.c"
    "$EXT/org_brotli/c/common/transform.c"
    "$EXT/org_brotli/c/dec/bit_reader.c"
    "$EXT/org_brotli/c/dec/decode.c"
    "$EXT/org_brotli/c/dec/huffman.c"
    "$EXT/org_brotli/c/dec/state.c"
    "$EXT/org_brotli/c/enc/backward_references.c"
    "$EXT/org_brotli/c/enc/backward_references_hq.c"
    "$EXT/org_brotli/c/enc/bit_cost.c"
    "$EXT/org_brotli/c/enc/block_splitter.c"
    "$EXT/org_brotli/c/enc/brotli_bit_stream.c"
    "$EXT/org_brotli/c/enc/cluster.c"
    "$EXT/org_brotli/c/enc/command.c"
    "$EXT/org_brotli/c/enc/compound_dictionary.c"
    "$EXT/org_brotli/c/enc/compress_fragment.c"
    "$EXT/org_brotli/c/enc/compress_fragment_two_pass.c"
    "$EXT/org_brotli/c/enc/dictionary_hash.c"
    "$EXT/org_brotli/c/enc/encode.c"
    "$EXT/org_brotli/c/enc/encoder_dict.c"
    "$EXT/org_brotli/c/enc/entropy_encode.c"
    "$EXT/org_brotli/c/enc/fast_log.c"
    "$EXT/org_brotli/c/enc/histogram.c"
    "$EXT/org_brotli/c/enc/literal_cost.c"
    "$EXT/org_brotli/c/enc/memory.c"
    "$EXT/org_brotli/c/enc/metablock.c"
    "$EXT/org_brotli/c/enc/static_dict.c"
    "$EXT/org_brotli/c/enc/utf8_util.c"
)

ZSTD_DIR="$EXT/net_zstd"
ZSTD_C_SRCS=(
    "$ZSTD_DIR/common/debug.c"
    "$ZSTD_DIR/common/entropy_common.c"
    "$ZSTD_DIR/common/error_private.c"
    "$ZSTD_DIR/common/fse_decompress.c"
    "$ZSTD_DIR/common/pool.c"
    "$ZSTD_DIR/common/threading.c"
    "$ZSTD_DIR/common/xxhash.c"
    "$ZSTD_DIR/common/zstd_common.c"
    "$ZSTD_DIR/compress/fse_compress.c"
    "$ZSTD_DIR/compress/hist.c"
    "$ZSTD_DIR/compress/huf_compress.c"
    "$ZSTD_DIR/compress/zstd_compress.c"
    "$ZSTD_DIR/compress/zstd_compress_literals.c"
    "$ZSTD_DIR/compress/zstd_compress_sequences.c"
    "$ZSTD_DIR/compress/zstd_compress_superblock.c"
    "$ZSTD_DIR/compress/zstd_double_fast.c"
    "$ZSTD_DIR/compress/zstd_fast.c"
    "$ZSTD_DIR/compress/zstd_lazy.c"
    "$ZSTD_DIR/compress/zstd_ldm.c"
    "$ZSTD_DIR/compress/zstd_opt.c"
    "$ZSTD_DIR/compress/zstdmt_compress.c"
    "$ZSTD_DIR/decompress/huf_decompress.c"
    "$ZSTD_DIR/decompress/zstd_ddict.c"
    "$ZSTD_DIR/decompress/zstd_decompress.c"
    "$ZSTD_DIR/decompress/zstd_decompress_block.c"
)

ZSTD_CFLAGS=(-I "$ZSTD_DIR" -I "$ZSTD_DIR/common" -DZSTD_MULTITHREAD -DXXH_NAMESPACE=ZSTD_)

FAILED=0

compile_cc() {
    local src="$1"
    shift
    local obj="$OUTDIR/$(echo "$src" | tr '/.' '__').o"
    if $CXX "${CXXFLAGS[@]}" "$@" -c "$src" -o "$obj" 2>&1; then
        echo "  OK: $(basename $src)"
    else
        echo "  FAIL: $src"
        FAILED=1
    fi
}

compile_c() {
    local src="$1"
    shift
    local obj="$OUTDIR/$(echo "$src" | tr '/.' '__').o"
    if gcc -O2 -fPIC -DNDEBUG -fvisibility=hidden "$@" -c "$src" -o "$obj" 2>&1; then
        echo "  OK: $(basename $src)"
    else
        echo "  FAIL: $src"
        FAILED=1
    fi
}

# Compile C++ sources in parallel
for src in "${RIEGELI_SRCS[@]}" "${PROTO_SRCS[@]}" "${THIRDPARTY_SRCS[@]}"; do
    compile_cc "$src" &
done

# highwayhash with ISA flags
for src in "${HH_SSE41_SRCS[@]}"; do
    compile_cc "$src" -msse4.1 &
done
for src in "${HH_AVX2_SRCS[@]}"; do
    compile_cc "$src" -mavx2 &
done

# C sources: brotli
for src in "${BROTLI_C_SRCS[@]}"; do
    compile_c "$src" -I "$EXT/org_brotli/c/include" &
done

# C sources: zstd
for src in "${ZSTD_C_SRCS[@]}"; do
    compile_c "$src" "${ZSTD_CFLAGS[@]}" &
done

echo "Waiting for compilations..."
wait

if [ "$FAILED" -ne 0 ]; then
    echo "=== SOME COMPILATIONS FAILED ==="
    exit 1
fi

echo "=== All compilations done ==="
echo "=== Linking ==="

OBJS=("$OUTDIR"/*.o)
$CXX -shared -o "$OUTDIR/../_riegeli_dataset_ops.so" "${OBJS[@]}" \
    -Wl,--version-script="$GEN/hide_all.lds" \
    -L"$TF_DIR" -l:libtensorflow_framework.so.2 \
    -lpthread -lz

echo "=== Done ==="
ls -la "$OUTDIR/../_riegeli_dataset_ops.so"
