// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: riegeli/records/records_metadata.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_riegeli_2frecords_2frecords_5fmetadata_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_riegeli_2frecords_2frecords_5fmetadata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_riegeli_2frecords_2frecords_5fmetadata_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_riegeli_2frecords_2frecords_5fmetadata_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto;
namespace riegeli {
class RecordsMetadata;
struct RecordsMetadataDefaultTypeInternal;
extern RecordsMetadataDefaultTypeInternal _RecordsMetadata_default_instance_;
}  // namespace riegeli
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace riegeli {

// ===================================================================


// -------------------------------------------------------------------

class RecordsMetadata final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:riegeli.RecordsMetadata) */ {
 public:
  inline RecordsMetadata() : RecordsMetadata(nullptr) {}
  ~RecordsMetadata() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RecordsMetadata(
      ::google::protobuf::internal::ConstantInitialized);

  inline RecordsMetadata(const RecordsMetadata& from) : RecordsMetadata(nullptr, from) {}
  inline RecordsMetadata(RecordsMetadata&& from) noexcept
      : RecordsMetadata(nullptr, std::move(from)) {}
  inline RecordsMetadata& operator=(const RecordsMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecordsMetadata& operator=(RecordsMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecordsMetadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecordsMetadata* internal_default_instance() {
    return reinterpret_cast<const RecordsMetadata*>(
        &_RecordsMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RecordsMetadata& a, RecordsMetadata& b) { a.Swap(&b); }
  inline void Swap(RecordsMetadata* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecordsMetadata* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecordsMetadata* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<RecordsMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RecordsMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RecordsMetadata& from) { RecordsMetadata::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(RecordsMetadata* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "riegeli.RecordsMetadata"; }

 protected:
  explicit RecordsMetadata(::google::protobuf::Arena* arena);
  RecordsMetadata(::google::protobuf::Arena* arena, const RecordsMetadata& from);
  RecordsMetadata(::google::protobuf::Arena* arena, RecordsMetadata&& from) noexcept
      : RecordsMetadata(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFileDescriptorFieldNumber = 3,
    kFileCommentFieldNumber = 1,
    kRecordTypeNameFieldNumber = 2,
    kRecordWriterOptionsFieldNumber = 4,
    kNumRecordsFieldNumber = 5,
  };
  // repeated .google.protobuf.FileDescriptorProto file_descriptor = 3;
  int file_descriptor_size() const;
  private:
  int _internal_file_descriptor_size() const;

  public:
  void clear_file_descriptor() ;
  ::google::protobuf::FileDescriptorProto* mutable_file_descriptor(int index);
  ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>* mutable_file_descriptor();

  private:
  const ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>& _internal_file_descriptor() const;
  ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>* _internal_mutable_file_descriptor();
  public:
  const ::google::protobuf::FileDescriptorProto& file_descriptor(int index) const;
  ::google::protobuf::FileDescriptorProto* add_file_descriptor();
  const ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>& file_descriptor() const;
  // optional string file_comment = 1;
  bool has_file_comment() const;
  void clear_file_comment() ;
  const std::string& file_comment() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_file_comment(Arg_&& arg, Args_... args);
  std::string* mutable_file_comment();
  PROTOBUF_NODISCARD std::string* release_file_comment();
  void set_allocated_file_comment(std::string* value);

  private:
  const std::string& _internal_file_comment() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_comment(
      const std::string& value);
  std::string* _internal_mutable_file_comment();

  public:
  // optional string record_type_name = 2;
  bool has_record_type_name() const;
  void clear_record_type_name() ;
  const std::string& record_type_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_record_type_name(Arg_&& arg, Args_... args);
  std::string* mutable_record_type_name();
  PROTOBUF_NODISCARD std::string* release_record_type_name();
  void set_allocated_record_type_name(std::string* value);

  private:
  const std::string& _internal_record_type_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_record_type_name(
      const std::string& value);
  std::string* _internal_mutable_record_type_name();

  public:
  // optional string record_writer_options = 4;
  bool has_record_writer_options() const;
  void clear_record_writer_options() ;
  const std::string& record_writer_options() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_record_writer_options(Arg_&& arg, Args_... args);
  std::string* mutable_record_writer_options();
  PROTOBUF_NODISCARD std::string* release_record_writer_options();
  void set_allocated_record_writer_options(std::string* value);

  private:
  const std::string& _internal_record_writer_options() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_record_writer_options(
      const std::string& value);
  std::string* _internal_mutable_record_writer_options();

  public:
  // optional int64 num_records = 5;
  bool has_num_records() const;
  void clear_num_records() ;
  ::int64_t num_records() const;
  void set_num_records(::int64_t value);

  private:
  ::int64_t _internal_num_records() const;
  void _internal_set_num_records(::int64_t value);

  public:
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            typename = typename _proto_TypeTraits::Singular>
  inline bool HasExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.Has(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void ClearExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    _impl_._extensions_.ClearExtension(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            typename = typename _proto_TypeTraits::Repeated>
  inline int ExtensionSize(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.ExtensionSize(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<!_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Mutable(id.number(), _field_type, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::ConstType value) {
    _proto_TypeTraits::Set(id.number(), _field_type, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::SetAllocated(id.number(), _field_type, value,
                                    &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void UnsafeArenaSetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::UnsafeArenaSetAllocated(id.number(), _field_type,
                                               value, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  PROTOBUF_NODISCARD inline
      typename _proto_TypeTraits::Singular::MutableType
      ReleaseExtension(
          const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                           _field_type, _is_packed>& id) {
    return _proto_TypeTraits::Release(id.number(), _field_type, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType
  UnsafeArenaReleaseExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::UnsafeArenaRelease(id.number(), _field_type,
                                                 &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<!_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Mutable(id.number(), index, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index, typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Set(id.number(), index, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    typename _proto_TypeTraits::Repeated::MutableType to_add =
        _proto_TypeTraits::Add(id.number(), _field_type, &_impl_._extensions_);
    return to_add;
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Add(id.number(), _field_type, _is_packed, value,
                           &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline const typename _proto_TypeTraits::Repeated::RepeatedFieldType&
  GetRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::GetRepeated(id.number(), _impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::RepeatedFieldType*
  MutableRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<RecordsMetadata, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::MutableRepeated(id.number(), _field_type,
                                              _is_packed, &_impl_._extensions_);
  }
  // @@protoc_insertion_point(class_scope:riegeli.RecordsMetadata)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 1,
      81, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_RecordsMetadata_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RecordsMetadata& from_msg);
    ::google::protobuf::internal::ExtensionSet _extensions_;
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto > file_descriptor_;
    ::google::protobuf::internal::ArenaStringPtr file_comment_;
    ::google::protobuf::internal::ArenaStringPtr record_type_name_;
    ::google::protobuf::internal::ArenaStringPtr record_writer_options_;
    ::int64_t num_records_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_riegeli_2frecords_2frecords_5fmetadata_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RecordsMetadata

// optional string file_comment = 1;
inline bool RecordsMetadata::has_file_comment() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void RecordsMetadata::clear_file_comment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_comment_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RecordsMetadata::file_comment() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:riegeli.RecordsMetadata.file_comment)
  return _internal_file_comment();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RecordsMetadata::set_file_comment(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.file_comment_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:riegeli.RecordsMetadata.file_comment)
}
inline std::string* RecordsMetadata::mutable_file_comment() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_file_comment();
  // @@protoc_insertion_point(field_mutable:riegeli.RecordsMetadata.file_comment)
  return _s;
}
inline const std::string& RecordsMetadata::_internal_file_comment() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_comment_.Get();
}
inline void RecordsMetadata::_internal_set_file_comment(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.file_comment_.Set(value, GetArena());
}
inline std::string* RecordsMetadata::_internal_mutable_file_comment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.file_comment_.Mutable( GetArena());
}
inline std::string* RecordsMetadata::release_file_comment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:riegeli.RecordsMetadata.file_comment)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.file_comment_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.file_comment_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void RecordsMetadata::set_allocated_file_comment(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.file_comment_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.file_comment_.IsDefault()) {
          _impl_.file_comment_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:riegeli.RecordsMetadata.file_comment)
}

// optional string record_type_name = 2;
inline bool RecordsMetadata::has_record_type_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void RecordsMetadata::clear_record_type_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.record_type_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RecordsMetadata::record_type_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:riegeli.RecordsMetadata.record_type_name)
  return _internal_record_type_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RecordsMetadata::set_record_type_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.record_type_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:riegeli.RecordsMetadata.record_type_name)
}
inline std::string* RecordsMetadata::mutable_record_type_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_record_type_name();
  // @@protoc_insertion_point(field_mutable:riegeli.RecordsMetadata.record_type_name)
  return _s;
}
inline const std::string& RecordsMetadata::_internal_record_type_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.record_type_name_.Get();
}
inline void RecordsMetadata::_internal_set_record_type_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.record_type_name_.Set(value, GetArena());
}
inline std::string* RecordsMetadata::_internal_mutable_record_type_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.record_type_name_.Mutable( GetArena());
}
inline std::string* RecordsMetadata::release_record_type_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:riegeli.RecordsMetadata.record_type_name)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.record_type_name_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.record_type_name_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void RecordsMetadata::set_allocated_record_type_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.record_type_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.record_type_name_.IsDefault()) {
          _impl_.record_type_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:riegeli.RecordsMetadata.record_type_name)
}

// repeated .google.protobuf.FileDescriptorProto file_descriptor = 3;
inline int RecordsMetadata::_internal_file_descriptor_size() const {
  return _internal_file_descriptor().size();
}
inline int RecordsMetadata::file_descriptor_size() const {
  return _internal_file_descriptor_size();
}
inline ::google::protobuf::FileDescriptorProto* RecordsMetadata::mutable_file_descriptor(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:riegeli.RecordsMetadata.file_descriptor)
  return _internal_mutable_file_descriptor()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>* RecordsMetadata::mutable_file_descriptor()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:riegeli.RecordsMetadata.file_descriptor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_file_descriptor();
}
inline const ::google::protobuf::FileDescriptorProto& RecordsMetadata::file_descriptor(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:riegeli.RecordsMetadata.file_descriptor)
  return _internal_file_descriptor().Get(index);
}
inline ::google::protobuf::FileDescriptorProto* RecordsMetadata::add_file_descriptor() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::FileDescriptorProto* _add = _internal_mutable_file_descriptor()->Add();
  // @@protoc_insertion_point(field_add:riegeli.RecordsMetadata.file_descriptor)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>& RecordsMetadata::file_descriptor() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:riegeli.RecordsMetadata.file_descriptor)
  return _internal_file_descriptor();
}
inline const ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>&
RecordsMetadata::_internal_file_descriptor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_descriptor_;
}
inline ::google::protobuf::RepeatedPtrField<::google::protobuf::FileDescriptorProto>*
RecordsMetadata::_internal_mutable_file_descriptor() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.file_descriptor_;
}

// optional string record_writer_options = 4;
inline bool RecordsMetadata::has_record_writer_options() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void RecordsMetadata::clear_record_writer_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.record_writer_options_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& RecordsMetadata::record_writer_options() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:riegeli.RecordsMetadata.record_writer_options)
  return _internal_record_writer_options();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RecordsMetadata::set_record_writer_options(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.record_writer_options_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:riegeli.RecordsMetadata.record_writer_options)
}
inline std::string* RecordsMetadata::mutable_record_writer_options() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_record_writer_options();
  // @@protoc_insertion_point(field_mutable:riegeli.RecordsMetadata.record_writer_options)
  return _s;
}
inline const std::string& RecordsMetadata::_internal_record_writer_options() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.record_writer_options_.Get();
}
inline void RecordsMetadata::_internal_set_record_writer_options(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.record_writer_options_.Set(value, GetArena());
}
inline std::string* RecordsMetadata::_internal_mutable_record_writer_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.record_writer_options_.Mutable( GetArena());
}
inline std::string* RecordsMetadata::release_record_writer_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:riegeli.RecordsMetadata.record_writer_options)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.record_writer_options_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.record_writer_options_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void RecordsMetadata::set_allocated_record_writer_options(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.record_writer_options_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.record_writer_options_.IsDefault()) {
          _impl_.record_writer_options_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:riegeli.RecordsMetadata.record_writer_options)
}

// optional int64 num_records = 5;
inline bool RecordsMetadata::has_num_records() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void RecordsMetadata::clear_num_records() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_records_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t RecordsMetadata::num_records() const {
  // @@protoc_insertion_point(field_get:riegeli.RecordsMetadata.num_records)
  return _internal_num_records();
}
inline void RecordsMetadata::set_num_records(::int64_t value) {
  _internal_set_num_records(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:riegeli.RecordsMetadata.num_records)
}
inline ::int64_t RecordsMetadata::_internal_num_records() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_records_;
}
inline void RecordsMetadata::_internal_set_num_records(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_records_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace riegeli


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_riegeli_2frecords_2frecords_5fmetadata_2eproto_2epb_2eh
