// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: riegeli/records/records_metadata.proto
// Protobuf C++ Version: 5.28.3

#include "riegeli/records/records_metadata.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace riegeli {

inline constexpr RecordsMetadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        file_descriptor_{},
        file_comment_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        record_type_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        record_writer_options_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        num_records_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR RecordsMetadata::RecordsMetadata(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RecordsMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecordsMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecordsMetadataDefaultTypeInternal() {}
  union {
    RecordsMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecordsMetadataDefaultTypeInternal _RecordsMetadata_default_instance_;
}  // namespace riegeli
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_riegeli_2frecords_2frecords_5fmetadata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_riegeli_2frecords_2frecords_5fmetadata_2eproto = nullptr;
const ::uint32_t
    TableStruct_riegeli_2frecords_2frecords_5fmetadata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _internal_metadata_),
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _impl_._extensions_),
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _impl_.file_comment_),
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _impl_.record_type_name_),
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _impl_.file_descriptor_),
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _impl_.record_writer_options_),
        PROTOBUF_FIELD_OFFSET(::riegeli::RecordsMetadata, _impl_.num_records_),
        0,
        1,
        ~0u,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 13, -1, sizeof(::riegeli::RecordsMetadata)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::riegeli::_RecordsMetadata_default_instance_._instance,
};
const char descriptor_table_protodef_riegeli_2frecords_2frecords_5fmetadata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n&riegeli/records/records_metadata.proto"
    "\022\007riegeli\032 google/protobuf/descriptor.pr"
    "oto\"\277\001\n\017RecordsMetadata\022\024\n\014file_comment\030"
    "\001 \001(\t\022\030\n\020record_type_name\030\002 \001(\t\022=\n\017file_"
    "descriptor\030\003 \003(\0132$.google.protobuf.FileD"
    "escriptorProto\022\035\n\025record_writer_options\030"
    "\004 \001(\t\022\023\n\013num_records\030\005 \001(\003*\t\010\350\007\020\200\200\200\200\002"
};
static const ::_pbi::DescriptorTable* const descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto = {
    false,
    false,
    277,
    descriptor_table_protodef_riegeli_2frecords_2frecords_5fmetadata_2eproto,
    "riegeli/records/records_metadata.proto",
    &descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto_once,
    descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_riegeli_2frecords_2frecords_5fmetadata_2eproto::offsets,
    file_level_enum_descriptors_riegeli_2frecords_2frecords_5fmetadata_2eproto,
    file_level_service_descriptors_riegeli_2frecords_2frecords_5fmetadata_2eproto,
};
namespace riegeli {
// ===================================================================

class RecordsMetadata::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RecordsMetadata>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_._has_bits_);
};

void RecordsMetadata::clear_file_descriptor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_descriptor_.Clear();
}
RecordsMetadata::RecordsMetadata(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:riegeli.RecordsMetadata)
}
inline PROTOBUF_NDEBUG_INLINE RecordsMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::riegeli::RecordsMetadata& from_msg)
      : _extensions_{visibility, arena},
        _has_bits_{from._has_bits_},
        _cached_size_{0},
        file_descriptor_{visibility, arena, from.file_descriptor_},
        file_comment_(arena, from.file_comment_),
        record_type_name_(arena, from.record_type_name_),
        record_writer_options_(arena, from.record_writer_options_) {}

RecordsMetadata::RecordsMetadata(
    ::google::protobuf::Arena* arena,
    const RecordsMetadata& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RecordsMetadata* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);
  _impl_.num_records_ = from._impl_.num_records_;

  // @@protoc_insertion_point(copy_constructor:riegeli.RecordsMetadata)
}
inline PROTOBUF_NDEBUG_INLINE RecordsMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _extensions_{visibility, arena},
        _cached_size_{0},
        file_descriptor_{visibility, arena},
        file_comment_(arena),
        record_type_name_(arena),
        record_writer_options_(arena) {}

inline void RecordsMetadata::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.num_records_ = {};
}
RecordsMetadata::~RecordsMetadata() {
  // @@protoc_insertion_point(destructor:riegeli.RecordsMetadata)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RecordsMetadata::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.file_comment_.Destroy();
  _impl_.record_type_name_.Destroy();
  _impl_.record_writer_options_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    RecordsMetadata::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_RecordsMetadata_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            RecordsMetadata::IsInitializedImpl,
            &RecordsMetadata::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<RecordsMetadata>(),
            ::google::protobuf::Message::GetNewImpl<RecordsMetadata>(),
            ::google::protobuf::Message::GetClearImpl<RecordsMetadata>(), &RecordsMetadata::ByteSizeLong,
                &RecordsMetadata::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_._cached_size_),
            false,
        },
        &RecordsMetadata::kDescriptorMethods,
        &descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* RecordsMetadata::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 81, 2> RecordsMetadata::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_._extensions_),
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::riegeli::RecordsMetadata>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string file_comment = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.file_comment_)}},
    // optional string record_type_name = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.record_type_name_)}},
    // repeated .google.protobuf.FileDescriptorProto file_descriptor = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.file_descriptor_)}},
    // optional string record_writer_options = 4;
    {::_pbi::TcParser::FastSS1,
     {34, 2, 0, PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.record_writer_options_)}},
    // optional int64 num_records = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RecordsMetadata, _impl_.num_records_), 3>(),
     {40, 3, 0, PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.num_records_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string file_comment = 1;
    {PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.file_comment_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string record_type_name = 2;
    {PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.record_type_name_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated .google.protobuf.FileDescriptorProto file_descriptor = 3;
    {PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.file_descriptor_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string record_writer_options = 4;
    {PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.record_writer_options_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int64 num_records = 5;
    {PROTOBUF_FIELD_OFFSET(RecordsMetadata, _impl_.num_records_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::FileDescriptorProto>()},
  }}, {{
    "\27\14\20\0\25\0\0\0"
    "riegeli.RecordsMetadata"
    "file_comment"
    "record_type_name"
    "record_writer_options"
  }},
};

PROTOBUF_NOINLINE void RecordsMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:riegeli.RecordsMetadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  _impl_.file_descriptor_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.file_comment_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.record_type_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.record_writer_options_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.num_records_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RecordsMetadata::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RecordsMetadata& this_ = static_cast<const RecordsMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RecordsMetadata::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RecordsMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:riegeli.RecordsMetadata)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string file_comment = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_file_comment();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "riegeli.RecordsMetadata.file_comment");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional string record_type_name = 2;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_record_type_name();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "riegeli.RecordsMetadata.record_type_name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated .google.protobuf.FileDescriptorProto file_descriptor = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_file_descriptor_size());
               i < n; i++) {
            const auto& repfield = this_._internal_file_descriptor().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // optional string record_writer_options = 4;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_record_writer_options();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "riegeli.RecordsMetadata.record_writer_options");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // optional int64 num_records = 5;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<5>(
                    stream, this_._internal_num_records(), target);
          }

          // Extension range [1000, 536870912)
          target = this_._impl_._extensions_._InternalSerialize(
              internal_default_instance(), 1000, 536870912, target, stream);
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:riegeli.RecordsMetadata)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RecordsMetadata::ByteSizeLong(const MessageLite& base) {
          const RecordsMetadata& this_ = static_cast<const RecordsMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RecordsMetadata::ByteSizeLong() const {
          const RecordsMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:riegeli.RecordsMetadata)
          ::size_t total_size = 0;
          total_size += this_._impl_._extensions_.ByteSize();

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .google.protobuf.FileDescriptorProto file_descriptor = 3;
             {
              total_size += 1UL * this_._internal_file_descriptor_size();
              for (const auto& msg : this_._internal_file_descriptor()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000000fu) {
            // optional string file_comment = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_file_comment());
            }
            // optional string record_type_name = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_record_type_name());
            }
            // optional string record_writer_options = 4;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_record_writer_options());
            }
            // optional int64 num_records = 5;
            if (cached_has_bits & 0x00000008u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_num_records());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RecordsMetadata::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecordsMetadata*>(&to_msg);
  auto& from = static_cast<const RecordsMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:riegeli.RecordsMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_file_descriptor()->MergeFrom(
      from._internal_file_descriptor());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_file_comment(from._internal_file_comment());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_record_type_name(from._internal_record_type_name());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_record_writer_options(from._internal_record_writer_options());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.num_records_ = from._impl_.num_records_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecordsMetadata::CopyFrom(const RecordsMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:riegeli.RecordsMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RecordsMetadata::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const RecordsMetadata&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(
          internal_default_instance())) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_file_descriptor()))
    return false;
  return true;
}

void RecordsMetadata::InternalSwap(RecordsMetadata* PROTOBUF_RESTRICT other) {
  using std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.file_descriptor_.InternalSwap(&other->_impl_.file_descriptor_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_comment_, &other->_impl_.file_comment_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.record_type_name_, &other->_impl_.record_type_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.record_writer_options_, &other->_impl_.record_writer_options_, arena);
        swap(_impl_.num_records_, other->_impl_.num_records_);
}

::google::protobuf::Metadata RecordsMetadata::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace riegeli
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_riegeli_2frecords_2frecords_5fmetadata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
